name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm i
      
      - name: Package VS Code extension
        id: package
        uses: nhedger/package-vscode-extension@v1

      - name: Publish VS Code extension artifact
        uses: actions/upload-artifact@v4
        with:
            name: funkin-completer-build
            path: ${{ steps.package.outputs.packagePath }}
