name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Node.js
        uses: actions/setup-node@v3.4.0
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm ci
      
      - name: Package VS Code extension
        id: package
        uses: nhedger/package-vscode-extension@v1

      - name: Publish VS Code extension artifact
        uses: actions/upload-artifact@v3
        with:
            name: fsac-build
            path: ${{ steps.package.outputs.packagePath }}
